version: "3"

services:
  csingo-doc:
    container_name: csingo-doc
    image: cxy1620541673/gitbook:0.0.2
    ports:
      - 4000:4000
    volumes:
      - ./:/www
    command:
      - /bin/sh
      - -c
      - |
        rm -rf src/_book
        rm -rf docs
        ls -al
        gitbook init src
        gitbook install src
        gitbook build src docs
        ls -al
        # gitbook serve src

